export const properties = [
    {
      id: 1,
      title: "Elite Haven",
      location: "123 Kensington Avenue, London, UK",
      price: "2000/mo",
      type: "rent",
      featured: true,
      image: "/assets/f1.jpg",
      beds: 5,
      baths: 2,
      area: 2400,
      garage: 1,
    },
    {
      id: 2,
      title: "Prestige Manor",
      location: "45 Mayfair Street, London, UK",
      price: "5000/mo",
      type: "sale",
      featured: true,
      image: "/assets/f2.jpg",
      beds: 4,
      baths: 3,
      area: 2000,
      garage: 2,
    },
    {
      id: 3,
      title: "Royal Heights",
      location: "78 Belgravia Road, London, UK",
      price: "5000",
      type: "rent",
      featured: true,
      image: "/assets/f3.jpg",
      beds: 5,
      baths: 4,
      area: 2500,
      garage: 3,
    },
    {
      id: 4,
      title: "Elite Haven",
      location: "123 Kensington Avenue, London, UK",
      price: "2000",
      type: "rent",
      featured: true,
      image: "/assets/f1.jpg",
      beds: 5,
      baths: 4,
      area: 2500,
      garage: 3,
    },
    {
      id: 5,
      title: "Prestige Manor",
      location: "45 Mayfair Street, London, UK",
      price: "5000",
      type: "sale",
      featured: true,
      image: "/assets/f2.jpg",
      beds: 5,
      baths: 4,
      area: 2500,
      garage: 3,
    },
    {
      id: 6,
      title: "Royal Heights",
      location: "78 Belgravia Road, London, UK",
      price: "5000/mo",
      type: "rent",
      featured: false,
      image: "/assets/f3.jpg",
      beds: 5,
      baths: 4,
      area: 2500,
      garage: 3,
    },
    {
      id: 7,
      title: "Royal Heights",
      location: "78 Belgravia Road, London, UK",
      price: "5000/mo",
      type: "rent",
      featured: true,
      image: "/assets/f3.jpg",
      beds: 5,
      baths: 4,
      area: 2500,
      garage: 3,
    },
    {
      id: 8,
      title: "Elite Haven",
      location: "123 Kensington Avenue, London, UK",
      price: "2000/mo",
      type: "rent",
      featured: false,
      image: "/assets/f1.jpg",
      beds: 3,
      baths: 2,
      area: 1200,
      garage: 1,
    },
    {
      id: 9,
      title: "Prestige Manor",
      location: "45 Mayfair Street, London, UK",
      price: "5000/mo",
      type: "sale",
      featured: false,
      image: "/assets/f2.jpg",
      beds: 4,
      baths: 3,
      area: 2000,
      garage: 2,
    },
    {
      id: 10,
      title: "Royal Heights",
      location: "78 Belgravia Road, London, UK",
      price: "5000/mo",
      type: "rent",
      featured: false,
      image: "/assets/f3.jpg",
      beds: 5,
      baths: 4,
      area: 2500,
      garage: 3,
    },
    {
      id: 11,
      title: "Elite Haven",
      location: "123 Kensington Avenue, London, UK",
      price: "2000",
      type: "rent",
      featured: false,
      image: "/assets/f1.jpg",
      beds: 5,
      baths: 4,
      area: 2500,
      garage: 3,
    },
    {
      id: 12,
      title: "Royal Heights",
      location: "78 Belgravia Road, London, UK",
      price: "5000",
      type: "rent",
      featured: false,
      image: "/assets/f3.jpg",
      beds: 5,
      baths: 4,
      area: 2500,
      garage: 3,
    },
  ]
  